//! Generated by `xtask extract-params` from Boulder_Dash.nes — do not edit.

#[derive(Debug, Clone, Copy)]
pub struct CaveParam {
    /// Rockford's spawn cell (row, column) on the 40x22 field.
    pub spawn_row: u8,
    pub spawn_col: u8,
    pub diamond_points: u8,
    pub diamond_points_bonus: u8,
    /// Diamonds required to open the exit, per difficulty level 1-4.
    pub diamonds_needed: [u8; 4],
    /// Cave time in 64-frame units (~1.07 s at 60 Hz), per difficulty 1-4.
    pub cave_time: [u8; 4],
}

pub const CAVE_PARAMS: [CaveParam; 24] = [
    CaveParam { spawn_row: 2, spawn_col: 3, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [10, 12, 14, 16], cave_time: [120, 100, 100, 100] },
    CaveParam { spawn_row: 19, spawn_col: 18, diamond_points: 20, diamond_points_bonus: 50, diamonds_needed: [8, 9, 10, 11], cave_time: [150, 120, 100, 80] },
    CaveParam { spawn_row: 2, spawn_col: 3, diamond_points: 15, diamond_points_bonus: 25, diamonds_needed: [15, 20, 23, 24], cave_time: [200, 150, 120, 100] },
    CaveParam { spawn_row: 1, spawn_col: 1, diamond_points: 5, diamond_points_bonus: 10, diamonds_needed: [18, 27, 45, 55], cave_time: [150, 120, 150, 120] },
    CaveParam { spawn_row: 1, spawn_col: 1, diamond_points: 50, diamond_points_bonus: 90, diamonds_needed: [4, 5, 6, 8], cave_time: [150, 120, 100, 80] },
    CaveParam { spawn_row: 18, spawn_col: 3, diamond_points: 40, diamond_points_bonus: 60, diamonds_needed: [4, 5, 6, 8], cave_time: [150, 120, 120, 120] },
    CaveParam { spawn_row: 1, spawn_col: 20, diamond_points: 10, diamond_points_bonus: 20, diamonds_needed: [10, 15, 18, 20], cave_time: [200, 180, 180, 150] },
    CaveParam { spawn_row: 1, spawn_col: 20, diamond_points: 10, diamond_points_bonus: 20, diamonds_needed: [10, 12, 15, 18], cave_time: [200, 180, 150, 120] },
    CaveParam { spawn_row: 10, spawn_col: 7, diamond_points: 5, diamond_points_bonus: 10, diamonds_needed: [60, 90, 120, 140], cave_time: [200, 190, 180, 170] },
    CaveParam { spawn_row: 1, spawn_col: 13, diamond_points: 25, diamond_points_bonus: 60, diamonds_needed: [6, 8, 12, 12], cave_time: [200, 180, 200, 180] },
    CaveParam { spawn_row: 18, spawn_col: 20, diamond_points: 50, diamond_points_bonus: 70, diamonds_needed: [3, 4, 5, 6], cave_time: [200, 180, 150, 120] },
    CaveParam { spawn_row: 18, spawn_col: 3, diamond_points: 20, diamond_points_bonus: 40, diamonds_needed: [18, 18, 19, 19], cave_time: [250, 230, 200, 180] },
    CaveParam { spawn_row: 1, spawn_col: 18, diamond_points: 5, diamond_points_bonus: 8, diamonds_needed: [40, 45, 50, 55], cave_time: [200, 180, 150, 120] },
    CaveParam { spawn_row: 1, spawn_col: 3, diamond_points: 10, diamond_points_bonus: 20, diamonds_needed: [15, 25, 35, 40], cave_time: [200, 180, 150, 120] },
    CaveParam { spawn_row: 1, spawn_col: 20, diamond_points: 10, diamond_points_bonus: 20, diamonds_needed: [10, 15, 20, 25], cave_time: [200, 180, 150, 120] },
    CaveParam { spawn_row: 1, spawn_col: 1, diamond_points: 10, diamond_points_bonus: 20, diamonds_needed: [8, 10, 25, 35], cave_time: [220, 200, 190, 180] },
    CaveParam { spawn_row: 14, spawn_col: 13, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [40, 45, 50, 56], cave_time: [130, 120, 110, 100] },
    CaveParam { spawn_row: 2, spawn_col: 1, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [80, 82, 84, 85], cave_time: [110, 100, 100, 90] },
    CaveParam { spawn_row: 1, spawn_col: 24, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [35, 40, 40, 45], cave_time: [100, 110, 120, 130] },
    CaveParam { spawn_row: 2, spawn_col: 10, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [50, 70, 90, 85], cave_time: [110, 110, 140, 130] },
    CaveParam { spawn_row: 10, spawn_col: 25, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [80, 90, 115, 120], cave_time: [220, 210, 210, 200] },
    CaveParam { spawn_row: 20, spawn_col: 1, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [60, 65, 77, 80], cave_time: [190, 190, 190, 190] },
    CaveParam { spawn_row: 6, spawn_col: 19, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [65, 70, 70, 80], cave_time: [200, 200, 220, 250] },
    CaveParam { spawn_row: 4, spawn_col: 20, diamond_points: 10, diamond_points_bonus: 15, diamonds_needed: [20, 20, 40, 50], cave_time: [170, 160, 150, 190] },
];

pub const PASSWORDS: [[u8; 8]; 24] = [
    [0, 0, 0, 0, 0, 0, 0, 0],
    [6, 3, 5, 8, 7, 0, 0, 16],
    [8, 4, 0, 1, 3, 7, 0, 32],
    [8, 4, 0, 9, 6, 7, 0, 48],
    [2, 2, 5, 3, 7, 8, 0, 64],
    [7, 5, 2, 0, 5, 3, 0, 80],
    [4, 2, 3, 4, 8, 0, 1, 0],
    [4, 5, 7, 3, 9, 7, 1, 16],
    [4, 3, 2, 5, 7, 9, 1, 32],
    [8, 6, 4, 1, 1, 1, 1, 48],
    [9, 9, 5, 0, 6, 5, 1, 64],
    [8, 2, 7, 1, 0, 0, 1, 80],
    [5, 3, 2, 3, 7, 5, 2, 0],
    [2, 4, 3, 4, 8, 1, 2, 16],
    [6, 0, 6, 6, 6, 4, 2, 32],
    [6, 9, 2, 5, 5, 1, 2, 48],
    [7, 2, 4, 8, 9, 2, 2, 64],
    [7, 7, 2, 9, 7, 4, 2, 80],
    [7, 2, 4, 0, 4, 5, 3, 0],
    [7, 2, 3, 8, 4, 6, 3, 16],
    [2, 3, 1, 7, 5, 0, 3, 32],
    [2, 2, 8, 7, 3, 3, 3, 48],
    [9, 2, 3, 8, 3, 8, 3, 64],
    [1, 8, 4, 9, 0, 4, 3, 80],
];

pub const PALETTE_MAIN: [u8; 32] = [0x22, 0x37, 0x27, 0x07,  0x22, 0x37, 0x29, 0x09,  0x22, 0x20, 0x10, 0x0F,  0x22, 0x20, 0x3A, 0x1A,  0x22, 0x36, 0x26, 0x0F,  0x22, 0x20, 0x10, 0x0F,  0x22, 0x20, 0x22, 0x0F,  0x22, 0x20, 0x10, 0x22];

pub const PALETTE_ALT_1: [u8; 32] = [0x22, 0x36, 0x00, 0x0F,  0x22, 0x20, 0x32, 0x0F,  0x22, 0x20, 0x32, 0x22,  0x22, 0x20, 0x16, 0x0F,  0x22, 0x36, 0x00, 0x0F,  0x22, 0x20, 0x32, 0x0F,  0x22, 0x20, 0x10, 0x0F,  0x22, 0x20, 0x16, 0x0F];

pub const PALETTE_ALT_2: [u8; 32] = [0x22, 0x20, 0x32, 0x12,  0x22, 0x29, 0x27, 0x0F,  0x22, 0x20, 0x10, 0x0F,  0x22, 0x20, 0x3A, 0x1A,  0x22, 0x20, 0x10, 0x00,  0x22, 0x29, 0x27, 0x0F,  0x22, 0x29, 0x10, 0x19,  0x22, 0x20, 0x3A, 0x1A];

pub const ROCKFORD_COLORS: [u8; 16] = [0x20, 0x21, 0x22, 0x23,  0x24, 0x25, 0x26, 0x27,  0x28, 0x29, 0x2A, 0x2B,  0x2C, 0x00, 0x10, 0x16];

/// Per-world gameplay palettes (CPU $BC28): 6 x 16 bytes = 4 bg groups
/// per world; byte 0 of each group is that world's backdrop color.
pub const WORLD_PALETTES: [[u8; 16]; 6] = [
    [0x0F, 0x20, 0x22, 0x12, 0x0F, 0x10, 0x00, 0x08, 0x0F, 0x27, 0x17, 0x07, 0x0F, 0x38, 0x15, 0x0F],
    [0x0C, 0x20, 0x23, 0x13, 0x0C, 0x27, 0x17, 0x0F, 0x0C, 0x32, 0x22, 0x12, 0x0C, 0x38, 0x12, 0x0F],
    [0x08, 0x20, 0x22, 0x12, 0x08, 0x20, 0x00, 0x0F, 0x08, 0x38, 0x28, 0x18, 0x08, 0x20, 0x16, 0x0F],
    [0x02, 0x20, 0x23, 0x13, 0x02, 0x12, 0x17, 0x07, 0x02, 0x29, 0x19, 0x09, 0x02, 0x20, 0x16, 0x0F],
    [0x08, 0x20, 0x22, 0x12, 0x08, 0x20, 0x10, 0x0F, 0x08, 0x29, 0x19, 0x0F, 0x08, 0x37, 0x16, 0x0F],
    [0x07, 0x20, 0x22, 0x12, 0x07, 0x20, 0x00, 0x0F, 0x07, 0x26, 0x16, 0x06, 0x07, 0x36, 0x18, 0x0F],
];
/// Canonical 2C02 master palette (RGB).
pub const NES_PALETTE: [[u8; 3]; 64] = [
    [84, 84, 84], [0, 30, 116], [8, 16, 144], [48, 0, 136], [68, 0, 100], [92, 0, 48], [84, 4, 0], [60, 24, 0], 
    [32, 42, 0], [8, 58, 0], [0, 64, 0], [0, 60, 0], [0, 50, 60], [0, 0, 0], [0, 0, 0], [0, 0, 0], 
    [152, 150, 152], [8, 76, 196], [48, 50, 236], [92, 30, 228], [136, 20, 176], [160, 20, 100], [152, 34, 32], [120, 60, 0], 
    [84, 90, 0], [40, 114, 0], [8, 124, 0], [0, 118, 40], [0, 102, 120], [0, 0, 0], [0, 0, 0], [0, 0, 0], 
    [236, 238, 236], [76, 154, 236], [120, 124, 236], [176, 98, 236], [228, 84, 236], [236, 88, 180], [236, 106, 100], [212, 136, 32], 
    [160, 170, 0], [116, 196, 0], [76, 208, 32], [56, 204, 108], [56, 180, 204], [60, 60, 60], [0, 0, 0], [0, 0, 0], 
    [236, 238, 236], [168, 204, 236], [188, 188, 236], [212, 178, 236], [236, 174, 236], [236, 174, 212], [236, 180, 176], [228, 196, 144], 
    [204, 210, 120], [180, 222, 120], [168, 226, 144], [152, 226, 180], [160, 214, 228], [160, 162, 160], [0, 0, 0], [0, 0, 0], 
];
