use crate::{rom::Rom, Ctx};
use anyhow::{ensure, Result};
use std::fmt::Write as _;

const CAVE_TABLE: u16 = 0xB86C;
const CAVE_COUNT: usize = 24;
const ROWS: usize = 22;
const COLS: usize = 40;
const PACKED_ROW: usize = COLS / 2; // 20 packed bytes per row
const CAVE_BYTES: usize = ROWS * PACKED_ROW; // 440

const SPACE: u8 = 0;
const MUD: u8 = 2;
const STEEL: u8 = 3;
const DOOR: u8 = 4;
const BRICK: u8 = 5;
const MAGIC: u8 = 6;
const BOULDER: u8 = 7;
const DIAMOND: u8 = 8;
const FIREFLY: u8 = 0xB;
const BUTTERFLY: u8 = 0xC;
const AMOEBA: u8 = 0xD;

struct CaveMeta {
    bank: usize,
    addr: u16,
}

pub fn extract(rom: &Rom, ctx: &Ctx) -> Result<()> {
    let mut caves = [[0u8; ROWS * COLS]; CAVE_COUNT];
    let mut metas = Vec::with_capacity(CAVE_COUNT);
    let mut all_anomalies = Vec::with_capacity(CAVE_COUNT);

    for i in 0..CAVE_COUNT {
        let e = CAVE_TABLE + (i * 3) as u16;
        let bank = rom.cpu(e) as usize;
        let addr = rom.cpu_u16(e + 1);
        ensure!(bank < 8, "cave {i}: CHR bank {bank} out of range");
        ensure!(
            (0x1000..=0x1FFF).contains(&addr),
            "cave {i}: PPU addr {addr:#06x} out of range"
        );
        let off = (addr - 0x1000) as usize;
        ensure!(
            off + CAVE_BYTES <= 0x1000,
            "cave {i}: 440 bytes at {addr:#06x} spill past 4KB bank {bank}"
        );
        let packed = &rom.chr_bank(bank)[off..off + CAVE_BYTES];

        for y in 0..ROWS {
            for p in 0..PACKED_ROW {
                let b = packed[y * PACKED_ROW + p];
                caves[i][y * COLS + 2 * p] = b & 0x0F; // low nibble = even column
                caves[i][y * COLS + 2 * p + 1] = b >> 4; // high nibble = odd column
            }
        }

        let anomalies = verify(i, &caves[i])?;
        metas.push(CaveMeta { bank, addr });
        all_anomalies.push(anomalies);
    }

    write_data(&caves, ctx)?;
    write_emoji_files(&caves, &metas, ctx)?;
    write_debug(&caves, &metas, &all_anomalies, ctx)?;
    print_summary(&caves, &metas, &all_anomalies);
    Ok(())
}

/// Checks the invariants from the extraction spec against the decoded grid.
/// Hard-fails on structural violations; returns a list of deviations from the
/// spec found in the actual ROM bytes:
/// - doors embedded in the outer border (border cells may be steel or door,
///   anything else is a hard error),
/// - caves with no diamond/butterfly/amoeba (e.g. magic-wall caves),
/// - nibbles 1/9/A/E/F, which per spec never occur in cave data.
fn verify(i: usize, grid: &[u8; ROWS * COLS]) -> Result<Vec<String>> {
    let mut anomalies = Vec::new();

    // Outer border: exactly 120 cells, steel wall (door allowed per above).
    let mut border = 0;
    for y in 0..ROWS {
        for x in 0..COLS {
            if y == 0 || y == ROWS - 1 || x == 0 || x == COLS - 1 {
                border += 1;
                let c = grid[y * COLS + x];
                ensure!(
                    c == STEEL || c == DOOR,
                    "cave {i}: border cell ({x},{y}) is {c:#X}, not steel wall/door"
                );
                if c == DOOR {
                    anomalies.push(format!("door-on-border({x},{y})"));
                }
            }
        }
    }
    ensure!(border == 120, "cave {i}: border has {border} cells, expected 120");

    let c = counts(grid);
    ensure!(
        c[DOOR as usize] == 1,
        "cave {i}: found {} doors, expected exactly 1",
        c[DOOR as usize]
    );

    if c[DIAMOND as usize] + c[BUTTERFLY as usize] + c[AMOEBA as usize] == 0 {
        anomalies.push("no diamond/butterfly/amoeba".to_string());
    }
    for nib in [1usize, 9, 0xA, 0xE, 0xF] {
        if c[nib] > 0 {
            anomalies.push(format!("forbidden-nibble-{nib:#X}x{}", c[nib]));
        }
    }
    Ok(anomalies)
}

fn counts(grid: &[u8; ROWS * COLS]) -> [usize; 16] {
    let mut c = [0usize; 16];
    for &cell in grid {
        c[cell as usize] += 1;
    }
    c
}

fn write_data(caves: &[[u8; ROWS * COLS]; CAVE_COUNT], ctx: &Ctx) -> Result<()> {
    let mut s = String::with_capacity(CAVE_COUNT * ROWS * COLS * 3 + 4096);
    s.push_str("//! Generated by `cargo run -p xtask -- extract-caves Boulder_Dash.nes`. Do not edit.\n");
    s.push_str("//! Cave maps decoded from CHR ROM: 40x22 cells, row-major (index = y*40+x).\n");
    s.push_str("//! Cell ids: 0=space 2=mud 3=steel 4=door 5=brick 6=magic 7=boulder\n");
    s.push_str("//!           8=diamond 0xB=firefly 0xC=butterfly 0xD=amoeba\n\n");
    let _ = writeln!(s, "pub const CAVE_COUNT: usize = {CAVE_COUNT};\n");
    let _ = writeln!(s, "pub const CAVES: [[u8; 880]; CAVE_COUNT] = [");
    for (i, cave) in caves.iter().enumerate() {
        let _ = writeln!(s, "    [ // cave {i}");
        for y in 0..ROWS {
            s.push_str("        ");
            for x in 0..COLS {
                let _ = write!(s, "{:2},", cave[y * COLS + x]);
            }
            let _ = writeln!(s, " // row {y}");
        }
        s.push_str("    ],\n");
    }
    s.push_str("];\n");
    s.push_str(
        r#"
/// Editable emoji cave files (one emoji per cell, space-separated, `#` comments).
/// These are the maps the game loads: edit `game/assets/caves/cave_XX.txt` and
/// rebuild to change a cave. `CAVES` above is the ROM-verified reference copy.
pub const CAVE_FILES: [&str; CAVE_COUNT] = [
"#,
    );
    for i in 0..CAVE_COUNT {
        let _ = writeln!(s, "    include_str!(\"../../assets/caves/cave_{i:02}.txt\"),");
    }
    s.push_str(
        r#"];

/// Cell id for an emoji token (variation selector U+FE0F stripped).
pub fn emoji_to_cell(token: &str) -> Option<u8> {
    Some(match token.trim_end_matches('\u{FE0F}') {
        "⬛" => 0,  // space
        "🟫" => 2,  // mud
        "⬜" => 3,  // steel wall
        "🚪" => 4,  // door (spawn + exit)
        "🧱" => 5,  // brick wall
        "✨" => 6,  // magic wall
        "🪨" => 7,  // boulder
        "💎" => 8,  // diamond
        "🐝" => 0xB, // firefly-class enemy
        "🦋" => 0xC, // butterfly-class enemy
        "🦠" => 0xD, // amoeba
        _ => return None,
    })
}

/// Parse an emoji cave file into a 40x22 grid (row-major, index = y*40+x).
/// Lines starting with `#` are comments. Returns None on unknown tokens
/// or a cell count other than 880.
pub fn parse_cave(text: &str) -> Option<[u8; 880]> {
    let mut cells = [0u8; 880];
    let mut n = 0;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        for tok in line.split_whitespace() {
            if n >= 880 {
                return None;
            }
            cells[n] = emoji_to_cell(tok)?;
            n += 1;
        }
    }
    (n == 880).then_some(cells)
}
"#,
    );
    let path = ctx.data_dir.join("caves.rs");
    std::fs::write(&path, s)?;
    eprintln!("wrote {}", path.display());
    Ok(())
}

fn ascii(cell: u8) -> char {
    match cell {
        SPACE => ' ',
        MUD => '.',
        STEEL => '#',
        DOOR => 'E',
        BRICK => '=',
        MAGIC => 'M',
        BOULDER => 'O',
        DIAMOND => '*',
        FIREFLY => 'f',
        BUTTERFLY => 'b',
        AMOEBA => 'a',
        _ => '?',
    }
}

fn write_debug(
    caves: &[[u8; ROWS * COLS]; CAVE_COUNT],
    metas: &[CaveMeta],
    all_anomalies: &[Vec<String>],
    ctx: &Ctx,
) -> Result<()> {
    let mut s = String::new();
    s.push_str("Boulder Dash (NES) cave maps — decoded from CHR ROM\n");
    s.push_str("charset: ' '=space '.'=mud '#'=steel 'E'=door '='=brick 'M'=magic\n");
    s.push_str("         'O'=boulder '*'=diamond 'f'=firefly 'b'=butterfly 'a'=amoeba '?'=other\n\n");
    for (i, cave) in caves.iter().enumerate() {
        let m = &metas[i];
        let c = counts(cave);
        let _ = writeln!(
            s,
            "cave {i:2}  (CHR bank {}, PPU ${:04X})  diamonds={} boulders={} fireflies={} butterflies={} amoeba={} doors={}  anomalies=[{}]",
            m.bank, m.addr, c[DIAMOND as usize], c[BOULDER as usize],
            c[FIREFLY as usize], c[BUTTERFLY as usize], c[AMOEBA as usize],
            c[DOOR as usize], all_anomalies[i].join(", "),
        );
        for y in 0..ROWS {
            for x in 0..COLS {
                s.push(ascii(cave[y * COLS + x]));
            }
            s.push('\n');
        }
        s.push('\n');
    }
    let path = ctx.assets_dir.join("caves_debug.txt");
    std::fs::write(&path, s)?;
    eprintln!("wrote {}", path.display());
    Ok(())
}

fn emoji(cell: u8) -> &'static str {
    match cell {
        SPACE => "⬛",
        MUD => "🟫",
        STEEL => "⬜",
        DOOR => "🚪",
        BRICK => "🧱",
        MAGIC => "✨",
        BOULDER => "🪨",
        DIAMOND => "💎",
        FIREFLY => "🐝",
        BUTTERFLY => "🦋",
        AMOEBA => "🦠",
        _ => "❓",
    }
}

/// Inverse of `emoji`, for the round-trip check (mirrors the parser that
/// xtask emits into game/src/data/caves.rs).
fn emoji_to_cell(tok: &str) -> Option<u8> {
    Some(match tok.trim_end_matches('\u{FE0F}') {
        "⬛" => SPACE,
        "🟫" => MUD,
        "⬜" => STEEL,
        "🚪" => DOOR,
        "🧱" => BRICK,
        "✨" => MAGIC,
        "🪨" => BOULDER,
        "💎" => DIAMOND,
        "🐝" => FIREFLY,
        "🦋" => BUTTERFLY,
        "🦠" => AMOEBA,
        _ => return None,
    })
}

fn write_emoji_files(
    caves: &[[u8; ROWS * COLS]; CAVE_COUNT],
    metas: &[CaveMeta],
    ctx: &Ctx,
) -> Result<()> {
    let dir = ctx.assets_dir.join("caves");
    std::fs::create_dir_all(&dir)?;
    for (i, cave) in caves.iter().enumerate() {
        let m = &metas[i];
        let mut s = String::new();
        let _ = writeln!(
            s,
            "# Boulder Dash cave {i} (world {}, town {}) — CHR bank {}, PPU ${:04X}",
            i / 4 + 1,
            i % 4 + 1,
            m.bank,
            m.addr,
        );
        s.push_str("# Edit freely: one emoji per cell, 40 columns x 22 rows, space-separated.\n");
        s.push_str("# Legend: ⬛ space · 🟫 mud · ⬜ steel wall · 🚪 door · 🧱 brick wall · ✨ magic wall\n");
        s.push_str("#         🪨 boulder · 💎 diamond · 🐝 firefly · 🦋 butterfly · 🦠 amoeba\n");
        for y in 0..ROWS {
            s.push('\n');
            let mut row = String::new();
            for x in 0..COLS {
                row.push_str(emoji(cave[y * COLS + x]));
                row.push(' ');
            }
            s.push_str(row.trim_end());
        }
        s.push('\n');

        // Round-trip check: the file must parse back to the exact ROM grid.
        let mut cells = Vec::with_capacity(ROWS * COLS);
        for line in s.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            for tok in line.split_whitespace() {
                cells.push(
                    emoji_to_cell(tok)
                        .ok_or_else(|| anyhow::anyhow!("cave {i}: bad emoji token {tok:?}"))?,
                );
            }
        }
        ensure!(
            cells.len() == ROWS * COLS,
            "cave {i}: emoji file has {} cells, expected {}",
            cells.len(),
            ROWS * COLS
        );
        ensure!(
            cells[..] == cave[..],
            "cave {i}: emoji round-trip mismatch vs ROM grid"
        );

        let path = dir.join(format!("cave_{i:02}.txt"));
        std::fs::write(&path, &s)?;
    }
    eprintln!("wrote {} emoji cave files to {}", CAVE_COUNT, dir.display());
    Ok(())
}

fn print_summary(
    caves: &[[u8; ROWS * COLS]; CAVE_COUNT],
    metas: &[CaveMeta],
    all_anomalies: &[Vec<String>],
) {
    println!("cave | bank addr   | dia bld fir btf amo | door | anomalies");
    println!("-----+-------------+---------------------+------+--------------------");
    for (i, cave) in caves.iter().enumerate() {
        let c = counts(cave);
        let m = &metas[i];
        let anomalies = if all_anomalies[i].is_empty() {
            "-".to_string()
        } else {
            all_anomalies[i].join(" ")
        };
        println!(
            "{i:4} | {} ${:04X}   | {:3} {:3} {:3} {:3} {:3} | {:4} | {}",
            m.bank,
            m.addr,
            c[DIAMOND as usize],
            c[BOULDER as usize],
            c[FIREFLY as usize],
            c[BUTTERFLY as usize],
            c[AMOEBA as usize],
            c[DOOR as usize],
            anomalies,
        );
    }
}
