//! CHR graphics extraction: 2bpp planar tiles, object metatile table,
//! and debug PNG atlases.

use crate::{rom::Rom, Ctx};
use anyhow::{ensure, Context, Result};
use std::fmt::Write as _;
use std::path::Path;

const TILE_COUNT: usize = 2048; // 32 KB CHR-ROM / 16 bytes per tile
const TILES_PER_BANK: usize = 256; // 4 KB MMC1 bank
const BANK_COUNT: usize = 8;

/// CPU address of the object metatile pointer table: 16 little-endian u16
/// pointers, one per cave object.
const METATILE_PTR_TABLE: u16 = 0xF383;
const METATILE_COUNT: usize = 16;
/// CPU address of the 16 per-object palette-attribute bytes, located right
/// after the last metatile quad record ($F44F + 4 bytes). NOTE: offsets in
/// the original notes were shifted by $10 (claimed quads $F3A3-$F462, attrs
/// $F463-$F472); the actual ROM has quads at $F3A3-$F452 and attrs at
/// $F453-$F462 — the 16 bytes there are all <= 3 (palette indices), while
/// $F463 onwards holds ascending tile indices (40 41 42 ...) of another table.
const METATILE_ATTRS_ADDR: u16 = 0xF453;

/// Tiles 1665-1674 digits 0-9, 1675-1700 letters A-Z, 1701-1712 icons.
const FONT_TILE_FIRST: usize = 1665;
const FONT_TILE_LAST: usize = 1712;

const GRAY: [u8; 4] = [0x00, 0x55, 0xAA, 0xFF];

/// Unpack one 8x8 2bpp tile (16 bytes at chr offset `tile * 16`) into 64
/// pixel color indices, row-major. Bit 7 of each plane byte is the leftmost
/// pixel; color = plane0_bit | plane1_bit << 1.
fn decode_tile(chr: &[u8], tile: usize) -> [u8; 64] {
    let base = tile * 16;
    let mut px = [0u8; 64];
    for row in 0..8 {
        let p0 = chr[base + row];
        let p1 = chr[base + 8 + row];
        for col in 0..8 {
            let bit = 7 - col;
            px[row * 8 + col] = ((p0 >> bit) & 1) | (((p1 >> bit) & 1) << 1);
        }
    }
    px
}

fn is_empty_tile(px: &[u8; 64]) -> bool {
    px.iter().all(|&p| p == 0)
}

fn write_tiles_rs(rom: &Rom, ctx: &Ctx) -> Result<[[u8; 4]; METATILE_COUNT]> {
    let mut out = String::with_capacity(TILE_COUNT * 64 * 3 + 4096);
    out.push_str("//! Generated by `xtask extract-chr` — do not edit.\n\n");
    out.push_str("pub const TILE_COUNT: usize = 2048;\n\n");

    out.push_str("/// Unpacked 8x8 pixel color indices (0-3), row-major, one entry per CHR tile.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const TILES: [[u8; 64]; TILE_COUNT] = [\n");
    for t in 0..TILE_COUNT {
        let px = decode_tile(&rom.chr, t);
        out.push_str("    [");
        for (i, p) in px.iter().enumerate() {
            if i > 0 {
                out.push(',');
            }
            let _ = write!(out, "{p}");
        }
        out.push_str("],\n");
    }
    out.push_str("];\n\n");

    // Object metatile table: 16 LE u16 pointers at $F383, each pointing at a
    // 4-byte record: the base animation frame as a 2x2 tile quad (indices are
    // relative to the world's pattern table).
    let ptr_table_end = METATILE_PTR_TABLE + 2 * METATILE_COUNT as u16;
    let mut metatiles = [[0u8; 4]; METATILE_COUNT];
    for (i, mt) in metatiles.iter_mut().enumerate() {
        let ptr = rom.cpu_u16(METATILE_PTR_TABLE + 2 * i as u16);
        ensure!(
            ptr >= ptr_table_end,
            "metatile ptr {i} = ${ptr:04X} points into the pointer table"
        );
        mt.copy_from_slice(rom.cpu_slice(ptr, 4));
    }

    out.push_str("/// Base 2x2 tile quad for each of the 16 cave objects (pointer table at $F383).\n");
    out.push_str("pub const METATILES: [[u8; 4]; 16] = [\n");
    for mt in &metatiles {
        let _ = writeln!(
            out,
            "    [0x{:02X}, 0x{:02X}, 0x{:02X}, 0x{:02X}],",
            mt[0], mt[1], mt[2], mt[3]
        );
    }
    out.push_str("];\n\n");

    let attrs = rom.cpu_slice(METATILE_ATTRS_ADDR, METATILE_COUNT);
    ensure!(
        attrs.iter().all(|&a| a <= 3),
        "metatile attrs at ${METATILE_ATTRS_ADDR:04X} are not palette indices 0-3: {attrs:02X?}"
    );
    out.push_str("/// Per-object palette attribute bytes (at $F453, right after the quad records).\n");
    out.push_str("pub const METATILE_ATTRS: [u8; 16] = [");
    for (i, a) in attrs.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        let _ = write!(out, "{a}");
    }
    out.push_str("];\n");

    // Full animation sequences: each pointer's record runs until the next
    // higher pointer (or the attrs table at $F453). Records are 4-byte quads.
    let mut ptrs = [0u16; METATILE_COUNT];
    for (i, p) in ptrs.iter_mut().enumerate() {
        *p = rom.cpu_u16(METATILE_PTR_TABLE + 2 * i as u16);
    }
    const MAX_FRAMES: usize = 9;
    let mut seq_lens = [0usize; METATILE_COUNT];
    let mut seqs = [[0u8; MAX_FRAMES * 4]; METATILE_COUNT];
    for i in 0..METATILE_COUNT {
        let end = ptrs
            .iter()
            .copied()
            .filter(|&p| p > ptrs[i])
            .min()
            .unwrap_or(METATILE_ATTRS_ADDR);
        let len = (end - ptrs[i]) as usize;
        ensure!(
            len % 4 == 0 && len >= 4,
            "metatile {i}: record at ${:04X} has bad length {len}",
            ptrs[i]
        );
        let frames = (len / 4).min(MAX_FRAMES);
        seq_lens[i] = frames;
        let rec = rom.cpu_slice(ptrs[i], frames * 4);
        for f in 0..MAX_FRAMES {
            // Pad by repeating the last real frame so naive indexers stay valid.
            let src = &rec[4 * f.min(frames - 1)..4 * f.min(frames - 1) + 4];
            seqs[i][4 * f..4 * f + 4].copy_from_slice(src);
        }
    }
    out.push_str("\n/// Animation frames per object (number of valid 2x2 quads in METATILE_SEQS).\n");
    out.push_str(&format!("pub const METATILE_SEQ_LEN: [usize; 16] = {seq_lens:?};\n\n"));
    out.push_str("/// Full animation sequences: 9 quads per object, padded by repeating the last frame.\n");
    out.push_str("#[rustfmt::skip]\n");
    out.push_str("pub const METATILE_SEQS: [[u8; 36]; 16] = [\n");
    for seq in &seqs {
        let _ = writeln!(out, "    {seq:?},");
    }
    out.push_str("];\n");

    let path = ctx.data_dir.join("tiles.rs");
    std::fs::write(&path, out).with_context(|| format!("write {}", path.display()))?;
    Ok(metatiles)
}

/// Blit a decoded tile into a grayscale image at tile grid position
/// (tx, ty) with integer `scale`.
fn blit_tile(img: &mut [u8], img_w: usize, px: &[u8; 64], tx: usize, ty: usize, scale: usize) {
    for row in 0..8 {
        for col in 0..8 {
            let g = GRAY[px[row * 8 + col] as usize];
            for dy in 0..scale {
                for dx in 0..scale {
                    img[(ty * 8 * scale + row * scale + dy) * img_w
                        + tx * 8 * scale
                        + col * scale
                        + dx] = g;
                }
            }
        }
    }
}

fn write_png(path: &Path, width: u32, height: u32, pixels: &[u8]) -> Result<()> {
    let file = std::fs::File::create(path).with_context(|| format!("create {}", path.display()))?;
    let mut enc = png::Encoder::new(file, width, height);
    enc.set_color(png::ColorType::Grayscale);
    enc.set_depth(png::BitDepth::Eight);
    let mut writer = enc.write_header()?;
    writer
        .write_image_data(pixels)
        .with_context(|| format!("encode {}", path.display()))?;
    Ok(())
}

/// Render one 4 KB MMC1 CHR bank as a 16x16-tile atlas, 2x scale, grayscale.
fn render_bank_atlas(rom: &Rom, ctx: &Ctx, bank: usize) -> Result<usize> {
    let scale = 2;
    let side = 16 * 8 * scale;
    let mut img = vec![0u8; side * side];
    let mut non_empty = 0;
    for t in 0..TILES_PER_BANK {
        let px = decode_tile(rom.chr_bank(bank), t);
        if !is_empty_tile(&px) {
            non_empty += 1;
        }
        blit_tile(&mut img, side, &px, t % 16, t / 16, scale);
    }
    let path = ctx.assets_dir.join(format!("chr_bank{bank}.png"));
    write_png(&path, side as u32, side as u32, &img)?;
    Ok(non_empty)
}

/// Tiles 1665-1712 (digits, letters, icons) in one row, 4x scale.
fn render_font_zoom(rom: &Rom, ctx: &Ctx) -> Result<()> {
    let scale = 4;
    let count = FONT_TILE_LAST - FONT_TILE_FIRST + 1;
    let w = count * 8 * scale;
    let h = 8 * scale;
    let mut img = vec![0u8; w * h];
    for (i, t) in (FONT_TILE_FIRST..=FONT_TILE_LAST).enumerate() {
        let px = decode_tile(&rom.chr, t);
        blit_tile(&mut img, w, &px, i, 0, scale);
    }
    write_png(&ctx.assets_dir.join("chr_font_zoom.png"), w as u32, h as u32, &img)
}

pub fn extract(rom: &Rom, ctx: &Ctx) -> Result<()> {
    ensure!(rom.chr.len() == TILE_COUNT * 16, "expected 32 KB CHR-ROM");

    let metatiles = write_tiles_rs(rom, ctx)?;

    // Spec checks: digit tile 1665 ('0') is non-empty, and object 3 (steel
    // wall) references tiles in 0x00-0x7F.
    let digit0 = decode_tile(&rom.chr, FONT_TILE_FIRST);
    ensure!(!is_empty_tile(&digit0), "digit tile 1665 is empty");
    ensure!(
        metatiles[3].iter().all(|&t| t <= 0x7F),
        "object 3 metatile out of range: {:02X?}",
        metatiles[3]
    );

    let mut counts = [0usize; BANK_COUNT];
    for (bank, count) in counts.iter_mut().enumerate() {
        *count = render_bank_atlas(rom, ctx, bank)?;
    }
    render_font_zoom(rom, ctx)?;

    println!("chr: non-empty tiles per bank: {counts:?} (total {})", counts.iter().sum::<usize>());
    println!("chr: metatiles:");
    for (i, mt) in metatiles.iter().enumerate() {
        let ptr = rom.cpu_u16(METATILE_PTR_TABLE + 2 * i as u16);
        let attr = rom.cpu(METATILE_ATTRS_ADDR + i as u16);
        println!(
            "  obj {i:2}: ptr=${ptr:04X} quad=[{:02X} {:02X} {:02X} {:02X}] attr={attr}",
            mt[0], mt[1], mt[2], mt[3]
        );
    }
    Ok(())
}
