use crate::{rom::Rom, Ctx};
use anyhow::{ensure, Result};
use std::fmt::Write as _;

const NUM_CAVES: usize = 24;
/// Pointer table: 24 LE u16 -> 12-byte cave parameter records.
const CAVE_PARAM_PTRS: u16 = 0xF233;
const CAVE_PARAM_LEN: usize = 12;
/// 24 records x 8 bytes: 6 password digit bytes + 2 suffix bytes.
const PASSWORDS_ADDR: u16 = 0xA927;
const PASSWORD_LEN: usize = 8;
/// Main 32-byte palette table (4 bg + 4 sprite groups).
const PALETTE_MAIN_ADDR: u16 = 0xA7D2;
/// Additional 32-byte palette table.
const PALETTE_ALT1_ADDR: u16 = 0xEA9E;
/// Additional 32-byte palette table (referenced from NMI path $A35B).
const PALETTE_ALT2_ADDR: u16 = 0xF0CA;
/// Rockford color choices, 16 bytes, indexed by (value & $0F).
/// Spec said $A763, but $A763 is 6502 code; the table is at $A769,
/// confirmed by `LDA $A769,Y` at CPU $A746 and $A7C8.
const ROCKFORD_COLORS_ADDR: u16 = 0xA769;

struct CaveParam {
    spawn_row: u8,
    spawn_col: u8,
    diamond_points: u8,
    diamond_points_bonus: u8,
    diamonds_needed: [u8; 4],
    cave_time: [u8; 4],
}

fn parse_cave_params(rom: &Rom) -> Result<Vec<CaveParam>> {
    let mut out = Vec::with_capacity(NUM_CAVES);
    for i in 0..NUM_CAVES {
        let ptr = rom.cpu_u16(CAVE_PARAM_PTRS + (i * 2) as u16);
        ensure!(
            (0x8000..=0xFFFF - CAVE_PARAM_LEN as u32 as u16).contains(&ptr),
            "cave param pointer {i} out of PRG range: ${ptr:04X}"
        );
        let rec = rom.cpu_slice(ptr, CAVE_PARAM_LEN);
        let mut diamonds_needed = [0u8; 4];
        let mut cave_time = [0u8; 4];
        for lvl in 0..4 {
            diamonds_needed[lvl] = rec[4 + lvl * 2];
            cave_time[lvl] = rec[5 + lvl * 2];
        }
        // rec[0]/rec[1] are Rockford's spawn cell (row, col) — confirmed by the
        // spawn write at $BE80 (`field[row=b0][col=b1] = $E0`). They are NOT
        // amoeba/magic-wall timers (those are hardcoded mechanics).
        out.push(CaveParam {
            spawn_row: rec[0],
            spawn_col: rec[1],
            diamond_points: rec[2],
            diamond_points_bonus: rec[3],
            diamonds_needed,
            cave_time,
        });
    }
    // Sanity: cave 0, difficulty 1 = 10 diamonds / 120 seconds.
    ensure!(
        out[0].diamonds_needed[0] == 10 && out[0].cave_time[0] == 120,
        "sanity failed: cave 0 L1 = {} diamonds / {} s (expected 10/120)",
        out[0].diamonds_needed[0],
        out[0].cave_time[0]
    );
    Ok(out)
}

fn parse_passwords(rom: &Rom) -> Result<[[u8; 8]; NUM_CAVES]> {
    let mut out = [[0u8; 8]; NUM_CAVES];
    for (i, rec) in out.iter_mut().enumerate() {
        rec.copy_from_slice(rom.cpu_slice(PASSWORDS_ADDR + (i * PASSWORD_LEN) as u16, PASSWORD_LEN));
    }
    ensure!(
        out[0][..6].iter().all(|&b| b == 0),
        "sanity failed: password record 0 first 6 bytes not zero: {:02X?}",
        &out[0][..6]
    );
    Ok(out)
}

/// Canonical 2C02 master palette (NesDev wiki RGB values), 64 entries.
const NES_PALETTE: [[u8; 3]; 64] = [
    [84, 84, 84], [0, 30, 116], [8, 16, 144], [48, 0, 136], [68, 0, 100], [92, 0, 48],
    [84, 4, 0], [60, 24, 0], [32, 42, 0], [8, 58, 0], [0, 64, 0], [0, 60, 0], [0, 50, 60],
    [0, 0, 0], [0, 0, 0], [0, 0, 0],
    [152, 150, 152], [8, 76, 196], [48, 50, 236], [92, 30, 228], [136, 20, 176], [160, 20, 100],
    [152, 34, 32], [120, 60, 0], [84, 90, 0], [40, 114, 0], [8, 124, 0], [0, 118, 40],
    [0, 102, 120], [0, 0, 0], [0, 0, 0], [0, 0, 0],
    [236, 238, 236], [76, 154, 236], [120, 124, 236], [176, 98, 236], [228, 84, 236],
    [236, 88, 180], [236, 106, 100], [212, 136, 32], [160, 170, 0], [116, 196, 0], [76, 208, 32],
    [56, 204, 108], [56, 180, 204], [60, 60, 60], [0, 0, 0], [0, 0, 0],
    [236, 238, 236], [168, 204, 236], [188, 188, 236], [212, 178, 236], [236, 174, 236],
    [236, 174, 212], [236, 180, 176], [228, 196, 144], [204, 210, 120], [180, 222, 120],
    [168, 226, 144], [152, 226, 180], [160, 214, 228], [160, 162, 160], [0, 0, 0], [0, 0, 0],
];

fn hex_row(bytes: &[u8]) -> String {
    let mut s = String::new();
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push_str(if i % 4 == 0 { ",  " } else { ", " });
        }
        let _ = write!(s, "0x{b:02X}");
    }
    s
}

fn render_data_rs(
    params: &[CaveParam],
    passwords: &[[u8; 8]; NUM_CAVES],
    pal_main: &[u8],
    pal_alt1: &[u8],
    pal_alt2: &[u8],
    rockford: &[u8],
) -> String {
    let mut s = String::new();
    s.push_str("//! Generated by `xtask extract-params` from Boulder_Dash.nes — do not edit.\n\n");

    s.push_str("#[derive(Debug, Clone, Copy)]\npub struct CaveParam {\n");
    s.push_str("    /// Rockford's spawn cell (row, column) on the 40x22 field.\n");
    s.push_str("    pub spawn_row: u8,\n    pub spawn_col: u8,\n");
    s.push_str("    pub diamond_points: u8,\n    pub diamond_points_bonus: u8,\n");
    s.push_str("    /// Diamonds required to open the exit, per difficulty level 1-4.\n");
    s.push_str("    pub diamonds_needed: [u8; 4],\n");
    s.push_str("    /// Cave time in 64-frame units (~1.07 s at 60 Hz), per difficulty 1-4.\n");
    s.push_str("    pub cave_time: [u8; 4],\n}\n\n");

    s.push_str("pub const CAVE_PARAMS: [CaveParam; 24] = [\n");
    for p in params {
        let _ = writeln!(
            s,
            "    CaveParam {{ spawn_row: {}, spawn_col: {}, diamond_points: {}, \
             diamond_points_bonus: {}, diamonds_needed: {:?}, cave_time: {:?} }},",
            p.spawn_row,
            p.spawn_col,
            p.diamond_points,
            p.diamond_points_bonus,
            p.diamonds_needed,
            p.cave_time
        );
    }
    s.push_str("];\n\n");

    s.push_str("pub const PASSWORDS: [[u8; 8]; 24] = [\n");
    for rec in passwords {
        let _ = writeln!(s, "    {:?},", rec);
    }
    s.push_str("];\n\n");

    let _ = writeln!(s, "pub const PALETTE_MAIN: [u8; 32] = [{}];\n", hex_row(pal_main));
    let _ = writeln!(s, "pub const PALETTE_ALT_1: [u8; 32] = [{}];\n", hex_row(pal_alt1));
    let _ = writeln!(s, "pub const PALETTE_ALT_2: [u8; 32] = [{}];\n", hex_row(pal_alt2));
    let _ = writeln!(s, "pub const ROCKFORD_COLORS: [u8; 16] = [{}];\n", hex_row(rockford));

    s.push_str("/// Canonical 2C02 master palette (RGB).\n");
    s.push_str("pub const NES_PALETTE: [[u8; 3]; 64] = [\n");
    for row in NES_PALETTE.chunks(8) {
        s.push_str("    ");
        for c in row {
            let _ = write!(s, "[{}, {}, {}], ", c[0], c[1], c[2]);
        }
        s.push('\n');
    }
    s.push_str("];\n");
    s
}

/// L1 quotas at or above this count are unlikely to be satisfiable from
/// pre-placed diamonds alone; flag them for cross-check against decoded cave
/// maps (butterflies / amoeba produce extra diamonds).
const HIGH_QUOTA_FLAG: u8 = 40;

fn render_dump_txt(
    params: &[CaveParam],
    passwords: &[[u8; 8]; NUM_CAVES],
    pal_main: &[u8],
    pal_alt1: &[u8],
    pal_alt2: &[u8],
    rockford: &[u8],
) -> String {
    let mut s = String::new();
    s.push_str("Boulder Dash NES — cave parameters (from $F233 pointer table)\n");
    s.push_str("spawn = Rockford spawn row/col, need = diamonds required, time = cave time units (64 frames each), per difficulty level 1-4\n\n");
    s.push_str("cave | spawn r  c | pts bonus | L1 need/time | L2 need/time | L3 need/time | L4 need/time | note\n");
    s.push_str("-----+--------------+-----------+--------------+--------------+--------------+--------------+------\n");
    let mut flagged = Vec::new();
    for (i, p) in params.iter().enumerate() {
        let high = p.diamonds_needed[0] >= HIGH_QUOTA_FLAG;
        if high {
            flagged.push((i, p.diamonds_needed[0]));
        }
        let _ = writeln!(
            s,
            " {:2}  |   {:3}  {:3}  | {:3}  {:3}  |  {:3}  {:3}    |  {:3}  {:3}    |  {:3}  {:3}    |  {:3}  {:3}    | {}",
            i,
            p.spawn_row,
            p.spawn_col,
            p.diamond_points,
            p.diamond_points_bonus,
            p.diamonds_needed[0],
            p.cave_time[0],
            p.diamonds_needed[1],
            p.cave_time[1],
            p.diamonds_needed[2],
            p.cave_time[2],
            p.diamonds_needed[3],
            p.cave_time[3],
            if high { "HIGH QUOTA: check vs cave data (butterflies/amoeba?)" } else { "" }
        );
    }
    let _ = writeln!(
        s,
        "\nFlagged caves (L1 quota >= {HIGH_QUOTA_FLAG}): {}",
        if flagged.is_empty() {
            "none".to_string()
        } else {
            flagged
                .iter()
                .map(|(i, q)| format!("cave {i} ({q} diamonds)"))
                .collect::<Vec<_>>()
                .join(", ")
        }
    );

    s.push_str("\nPasswords (24 x 8 bytes at $A927: 6 digit bytes + 2 suffix bytes)\n\n");
    s.push_str("rec | digits        | suffix\n----+---------------+-------\n");
    for (i, rec) in passwords.iter().enumerate() {
        let digits: String = rec[..6]
            .iter()
            .map(|d| if *d <= 9 { (b'0' + d) as char } else { '?' })
            .collect();
        let _ = writeln!(
            s,
            " {:2} | {}  {:02X} {:02X} {:02X} {:02X} {:02X} {:02X} | {:02X} {:02X}",
            i, digits, rec[0], rec[1], rec[2], rec[3], rec[4], rec[5], rec[6], rec[7]
        );
    }

    s.push_str("\nPalettes (hex, NES color indices)\n\n");
    let _ = writeln!(s, "PALETTE_MAIN  ($A7D2): {}", hex_row(pal_main));
    let _ = writeln!(s, "PALETTE_ALT_1 ($EA9E): {}", hex_row(pal_alt1));
    let _ = writeln!(s, "PALETTE_ALT_2 ($F0CA): {}", hex_row(pal_alt2));
    let _ = writeln!(s, "ROCKFORD_COLORS ($A769, table referenced as LDA $A769,Y; spec said $A763 which is code): {}",
        hex_row(rockford));
    s
}

pub fn extract(rom: &Rom, ctx: &Ctx) -> Result<()> {
    let params = parse_cave_params(rom)?;
    let passwords = parse_passwords(rom)?;
    let pal_main = rom.cpu_slice(PALETTE_MAIN_ADDR, 32);
    let pal_alt1 = rom.cpu_slice(PALETTE_ALT1_ADDR, 32);
    let pal_alt2 = rom.cpu_slice(PALETTE_ALT2_ADDR, 32);
    let rockford = rom.cpu_slice(ROCKFORD_COLORS_ADDR, 16);

    let rs = render_data_rs(&params, &passwords, pal_main, pal_alt1, pal_alt2, rockford);
    std::fs::write(ctx.data_dir.join("cave_params.rs"), rs)?;

    let txt = render_dump_txt(&params, &passwords, pal_main, pal_alt1, pal_alt2, rockford);
    std::fs::write(ctx.assets_dir.join("params_dump.txt"), &txt)?;

    let flagged: Vec<usize> = params
        .iter()
        .enumerate()
        .filter(|(_, p)| p.diamonds_needed[0] >= HIGH_QUOTA_FLAG)
        .map(|(i, _)| i)
        .collect();
    println!(
        "params: 24 caves, 24 passwords, 3x32B palettes, 16B rockford colors; high-quota caves: {flagged:?}"
    );
    Ok(())
}
